[pytest]
testpaths = tests
python_files = test_*.py
pythonpath = 
    .
    layers/common-layer/python
addopts = 
    --verbose
    --cov=src
    --cov=layers
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning 